package model

import "time"

// Feed is a data model for a column of newsfeed
// It contains a series of Post
// UserId is a uuid generated to identify a user internally
// AuthId is generated by external authentication service "cognito"
// Name is user's name to display
type Feed struct {
	Id          string `gorm:"primaryKey"`
	CreatedAt   time.Time
	DeletedAt   time.Time
	Title       string
	CreatorID   *string
	Creator     User    `gorm:"constraint:OnUpdate:CASCADE,OnDelete:SET NULL;"`
	Subscribers []*User `json:"subscribers" gorm:"many2many:user_feed_subscription;"`
}
