// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FeedSeedStateInterface interface {
	IsFeedSeedStateInterface()
}

type UserSeedStateInterface interface {
	IsUserSeedStateInterface()
}

type CurosrInput struct {
	FeedID string `json:"feedId"`
	Start  int    `json:"start"`
	End    int    `json:"end"`
}

type FeedSeedState struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (FeedSeedState) IsFeedSeedStateInterface() {}

type FeedSeedStateInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type FeedsForUserInput struct {
	UserID  string         `json:"userId"`
	Limit   *int           `json:"limit"`
	Cursors []*CurosrInput `json:"cursors"`
}

type NewFeedInput struct {
	UserID        string  `json:"userId"`
	Name          string  `json:"name"`
	FilterSetting *string `json:"filterSetting"`
}

type NewPostInput struct {
	Title            string   `json:"title"`
	Content          string   `json:"content"`
	SourceID         string   `json:"sourceId"`
	SubSourceID      *string  `json:"subSourceId"`
	FeedsIDPublishTo []string `json:"feedsIdPublishTo"`
	SharedFromPostID *string  `json:"sharedFromPostID"`
}

type NewSourceInput struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
	Domain string `json:"domain"`
}

type NewSubSourceInput struct {
	UserID             string `json:"userId"`
	Name               string `json:"name"`
	ExternalIdentifier string `json:"externalIdentifier"`
	SourceID           string `json:"sourceId"`
}

type NewUserInput struct {
	Name string `json:"name"`
}

type SeedState struct {
	UserSeedState *UserSeedState   `json:"userSeedState"`
	FeedSeedState []*FeedSeedState `json:"feedSeedState"`
}

type SeedStateInput struct {
	UserSeedState *UserSeedStateInput   `json:"userSeedState"`
	FeedSeedState []*FeedSeedStateInput `json:"feedSeedState"`
}

type SubscribeInput struct {
	UserID string `json:"userId"`
	FeedID string `json:"feedId"`
}

type UserSeedState struct {
	Name       string `json:"name"`
	AvartarURL string `json:"avartarUrl"`
}

func (UserSeedState) IsUserSeedStateInterface() {}

type UserSeedStateInput struct {
	Name      string `json:"name"`
	AvatarURL string `json:"avatarUrl"`
}
