# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deduplicator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deduplicator.proto',
  package='protocol',
  syntax='proto3',
  serialized_options=b'Z0github.com/Luismorlan/newsmux/publisher/protocol',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x64\x65\x64uplicator.proto\x12\x08protocol\"1\n\x11GetSimHashRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\"$\n\x12GetSimHashResponse\x12\x0e\n\x06\x62inary\x18\x01 \x01(\t2Y\n\x0c\x44\x65\x64uplicator\x12I\n\nGetSimHash\x12\x1b.protocol.GetSimHashRequest\x1a\x1c.protocol.GetSimHashResponse\"\x00\x42\x32Z0github.com/Luismorlan/newsmux/publisher/protocolb\x06proto3'
)




_GETSIMHASHREQUEST = _descriptor.Descriptor(
  name='GetSimHashRequest',
  full_name='protocol.GetSimHashRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='protocol.GetSimHashRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='protocol.GetSimHashRequest.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=81,
)


_GETSIMHASHRESPONSE = _descriptor.Descriptor(
  name='GetSimHashResponse',
  full_name='protocol.GetSimHashResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='binary', full_name='protocol.GetSimHashResponse.binary', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['GetSimHashRequest'] = _GETSIMHASHREQUEST
DESCRIPTOR.message_types_by_name['GetSimHashResponse'] = _GETSIMHASHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSimHashRequest = _reflection.GeneratedProtocolMessageType('GetSimHashRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSIMHASHREQUEST,
  '__module__' : 'deduplicator_pb2'
  # @@protoc_insertion_point(class_scope:protocol.GetSimHashRequest)
  })
_sym_db.RegisterMessage(GetSimHashRequest)

GetSimHashResponse = _reflection.GeneratedProtocolMessageType('GetSimHashResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSIMHASHRESPONSE,
  '__module__' : 'deduplicator_pb2'
  # @@protoc_insertion_point(class_scope:protocol.GetSimHashResponse)
  })
_sym_db.RegisterMessage(GetSimHashResponse)


DESCRIPTOR._options = None

_DEDUPLICATOR = _descriptor.ServiceDescriptor(
  name='Deduplicator',
  full_name='protocol.Deduplicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=121,
  serialized_end=210,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSimHash',
    full_name='protocol.Deduplicator.GetSimHash',
    index=0,
    containing_service=None,
    input_type=_GETSIMHASHREQUEST,
    output_type=_GETSIMHASHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEDUPLICATOR)

DESCRIPTOR.services_by_name['Deduplicator'] = _DEDUPLICATOR

# @@protoc_insertion_point(module_scope)
