package models

// Feed is a data model for a column of newsfeed
// It contains a series of Post
// UserId is a uuid generated to identify a user internally
// AuthId is generated by external authentication service "cognito"
// Name is user's name to display
type Feed struct {
	FeedId  int64  `json:"feed_id"`
	Title   string `json:"title"`
	Creator User   `json:"creator"`
}
