package models

import (
	"gorm.io/gorm"
)

// Feed is a data model for a column of newsfeed
// It contains a series of Post
// UserId is a uuid generated to identify a user internally
// AuthId is generated by external authentication service "cognito"
// Name is user's name to display
type Feed struct {
	gorm.Model
	Title       string  `json:"title"`
	CreatorID   uint    `json:"creator_id"`
	Creator     User    `json:"creator"`
	Subscribers []*User `json:"subscribers" gorm:"many2many:user_feed_subscription;"`
}
