package models

// User is a data model for users
// UserId: a uuid generated to identify a user internally
// AuthId: generated by external authentication service "cognito"
// Name: user's name to display
type User struct {
	UserId int64  `json:"user_id"`
	AuthId string `json:"auth_id"`
	Name   string `json:"name"`
}
